Added moderation support
Salz0/telegram_flea pull request #34
Opened 2023-10-28 14:14 UTC by ishevche

Resolved issue #1.

Every listing, before being sent to a specified channel, is sent to a moderator, defined by its CHAT_ID in the `.env` file. 

For each listing, a moderator has two options: approve and decline. If the moderator approves the listing, it is posted to the channel, and the seller is notified with a message containing a button to revoke the listing. If the listing is declined, only a notification for the seller is sent.

Six newly created text variables are used: 
 - `bot.listing_approved{listing}` - notification for seller with listing approval
 - `bot.listing_declined{listing}` - notification for seller with listing approval
 - `bot.moderator_approval` - text displayed on the approve button for the moderator
 - `bot.moderator_declination` - text displayed on the decline button for the moderator
 - `bot.approved_successfully` - text contained in approving callback_query answer
 - `bot.declined_successfully` - text contained in declining callback_query answer

The first two variables accept listing - a text of the message displayed in the channel.

2023-10-28 14:59 UTC, Salz0 requested changes

2023-10-28 15:09 UTC, mykolasolodukha commented
@ishevche please merge the latest `master` into your feature branch.

2023-10-28 15:09 UTC, mykolasolodukha requested changes
@ishevche please merge the latest master into your feature branch.

2023-10-29 11:44 UTC, Salz0 requested changes
Hey, thanks again for this awesome PR, please review the suggestions I've put

2023-11-01 00:29 UTC, ishevche commented on keyboards.py
> +    return reply_markup
For each user and each listing, different keyboards have to be created, with the ID of the corresponding listing bound with this keyboard. As a result, each instance has to be created dynamically during the program's lifecycle, so they can not be initialized once the program starts as keyboards above.

2023-11-01 08:20 UTC, Salz0 commented on keyboards.py
> +    return reply_markup
Agreed
One question remains: Why have it async instead of simply def?

2023-11-01 13:17 UTC, Salz0 commented
Great, thank you man for this big PR and for sticking to it util it's done. Highly appreciated 🙌

2023-11-01 13:17 UTC, merged