Add postgres in docker
Salz0/telegram_flea pull request #42
Opened 2023-10-28 15:18 UTC by hexponent

2023-11-04 18:21 UTC, mykolasolodukha requested changes
Safety concerns

2023-11-04 18:21 UTC, mykolasolodukha commented on docker-compose.yml
> +      - DATABASE_URL=postgres://postgres:123456@db:5432/postgres
Is it safe to run a `postgres` instance with such open credentials, given that we expose the `5432` port to external connections (line 16)?

2023-11-05 11:34 UTC, hexponent commented on docker-compose.yml
> +      - DATABASE_URL=postgres://postgres:123456@db:5432/postgres
You are right, its better to hide it, but I was waiting for postgres code to be merged. I will hide it here and also variables for db container as well

2023-11-05 22:00 UTC, Salz0 commented
@hexponent hey, if you could solve the conflicts and do the safety measure -- would be awesome! Will merge.

Postgres is now activated within the bot

2023-11-05 22:08 UTC, Salz0 requested changes
safety concern

2023-12-02 14:40 UTC, hexponent commented on docker-compose.yml
> +      - DATABASE_URL=postgres://postgres:123456@db:5432/postgres
@mykolasolodukha fixed

2023-12-04 18:47 UTC, merged

2023-12-04 18:47 UTC, Salz0 commented
Thank you! @hexponent